### ISSUE TITLE
where can i find the sent file

### ISSUE THREAD

**Issue by Ryuk17** [francesco-re-1107/serial-communicator#2]
Hi bro, i install your serial-communicator and sent a txt file to the serial port, but i cannot find the txt file in the system. Could you tell me where the file to be saved, thanks?

**Comment by francesco-re-1107** [comment]
Hi,
Are you using my serial-communicator on both sides of the transmission? In that case you should see the file in the receive text block and click on "save to file".
If you use my serial communicator only for sending and the receiver is another system I can't help you, you should read the manual of that system.

Regards
